name: Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-publish:
    name: Build and upload to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  ##most important
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y nvidia-cuda-toolkit
        python -m pip install --upgrade pip
        pip install build cmake ninja

    - name: Build and repair package
      run: |
        pip install auditwheel
        python -m build
        auditwheel repair dist/*.whl -w dist/fixed
        mv dist/fixed/* dist/
        rm -rf dist/fixed
        rm dist/*linux_x86_64.whl

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
